import type { AssetBaseDto } from './asset-base.dto';
import type { ContentExampleDto } from './content-example.dto';
import type { ContentExternalResourceDto } from './content-external-resource.dto';
import type { ContentMetricDto } from './content-metric.dto';
import type { ContentScenarioDto } from './content-scenario.dto';
import type { ContentTradeoffFactorDto } from './content-tradeoff-factor.dto';
import type { ContentUseCaseDto } from './content-use-case.dto';

export type ContentAssetDto = AssetBaseDto & {
  useCases: ContentUseCaseDto[];
  scenarios: ContentScenarioDto[];
  examples: ContentExampleDto[];
  resources: ContentExternalResourceDto[];
  tradeoffMatrix: ContentTradeoffFactorDto[];
  metrics: ContentMetricDto[];
  maturityLevel?: string;
  complexityLevel?: string;
  impacts?: string;
  decisionType?: string;
  organizationalMaturity?: string;
  valueStreamStage?: string;
  cognitiveLoad?: string;
  principles: string[];
  inputs: string[];
  outputs: string[];
  integrations: string[];
  architecturalDrivers: string[];
  bottleneckTags: string[];
  benefits: string[];
  limitations: string[];
  requiredSkills: string[];
  implementationSteps: string[];
  preconditions: string[];
  risks: string[];
  bestPractices: string[];
  antiPatterns: string[];
  techDebts: string[];
  misuseExamples: string[];
  traps: string[];
  constraints: string[];
  vendor?: string;
};
