export enum MatrixMode {
  SEGMENT_BY_PERSPECTIVE = 'SEGMENT_BY_PERSPECTIVE',
  ROLE_BY_PERSPECTIVE = 'ROLE_BY_PERSPECTIVE',
}

export enum MatrixPerspective {
  VALUE_STREAM = 'VALUE_STREAM',
  DECISION_TYPE = 'DECISION_TYPE',
  ORGANIZATIONAL_MATURITY = 'ORGANIZATIONAL_MATURITY',
}

export const VALUE_STREAM_BUCKETS = ['DISCOVERY', 'BUILD', 'RUN', 'ITERATE'];
export const DECISION_TYPE_BUCKETS = [
  'DESIGN_DECISION',
  'ARCHITECTURAL_DECISION',
  'ORGANIZATIONAL_DECISION',
  'TECHNOLOGY_DECISION',
];
export const ORGANIZATIONAL_MATURITY_BUCKETS = [
  'FOUNDATION',
  'INTERMEDIATE',
  'ADVANCED',
];

export type MatrixTagMap = Record<string, { de?: string; en?: string }>;
